---
# http://rubies.travis-ci.org/
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - ruby-head

env:
  - CHEF_LICENSE=accept-no-persist

bundler_args: --without integration
script: bundle exec rake
